Task 6: Cache scanned pages
dersnek/thinknetica-go pull request #6
Opened 2020-11-15 19:22 UTC by dersnek

**Сохранение данных поиска в файле.**

Для повторного использования полученных сканером данных требуется сохранить их в файле и восстановить при запуске программы. При этом после запуска поисковый движок всё равно должен отдать команду на сканирование сайтов, но до окончания сканирования он должен отдавать данные, загруженные из файла.

- **Разработать механизм записи полученных от сканера данных в файл.** Это должен делать поисковый движок по окончании сканирования сайтов. Формат представления данных для хранения выбирайте на своё усмотрение.
- **Загрузка данных из файла при старте поискового движка.** Эти данные должны использоваться для поисковой выдачи до окончания сканирования сайтов.
- **(Дополнительное) Разработать имитацию файловой системы в оперативной памяти и написать модульные тесты для сохранения и загрузки данных из файлов используя созданную имитацию файловой системы.** 

Дополнительное задание я не сделал.

2020-11-15 19:24 UTC, dersnek reviewed
LGTM

2020-11-17 05:00 UTC, DmitriyVTitov requested changes
Ошибка должна проверяться сразу же! Это очень серьёзная ошибка.

2020-11-17 05:00 UTC, DmitriyVTitov commented on task-6/cmd/go-search/main.go
> +
опять пустые строки?

2020-11-17 05:00 UTC, DmitriyVTitov commented on task-6/cmd/go-search/main.go
> +
уже неоднократно поправлял

2020-11-17 05:00 UTC, DmitriyVTitov commented on task-6/pkg/store/file/file.go
> +	}
ошибка должна проверяться сразу же! без какого-либо кода между местом появления и проверкой.
это крайне важно - источник паники!

2020-11-19 05:55 UTC, DmitriyVTitov approved these changes
OK. Однако у вас же есть пакет `store`, логично было бы там хранить отсканированные документы. Индекс для этого не предназначен.

2020-11-19 05:55 UTC, DmitriyVTitov commented on task-6/cmd/go-search/main.go
> +		fmt.Println(v)
`fmt.Printf("\n%v\n%v\n", k, v)`

2020-11-19 05:55 UTC, DmitriyVTitov commented on task-6/pkg/engine/engine.go
> +		fmt.Println("Running initial scan, this might take a while...")
подключаемый пакет ничего никуда печатать не должен (разве что в журнал).
кто и где это должен читать?

2020-11-19 05:55 UTC, DmitriyVTitov commented on task-6/pkg/engine/engine.go
> +	} else {
else - порочная практика.
я обычно не принимаю PR с `else` на работе.

2020-11-19 05:55 UTC, DmitriyVTitov commented on task-6/pkg/store/file/file.go
> +		Index: indx}
ужасное форматирование

2020-11-19 05:55 UTC, DmitriyVTitov commented on task-6/pkg/store/file/file.go
> +	encoder.Encode(is)
тут, насколько помню, тоже ошибка возможна

2020-11-19 05:55 UTC, DmitriyVTitov commented on task-6/pkg/store/file/file.go
> +	decoder.Decode(&is)
вот здесь, если правильно помню, тоже ошибка возможна

2020-11-19 05:55 UTC, DmitriyVTitov commented on task-6/pkg/store/file/file.go
> +	encoder.Encode(is)
и тут может быть ошибка

2020-11-22 14:33 UTC, merged